### ISSUE TITLE
Design Blue Print

### ISSUE THREAD

**Issue by lxiao6** [johnmottole/ssw322-group1#1]
1. Create the three design diagrams
2. Create paper prototype
3. Conduct usuability test
4. Prepare a 30 - 40 min presentation of your design blue print (Imagine you are trying to sell the design of your company). It shouldn't be a dry presentation of displaying the diagrams. Instead, try to tell us a story.

**Comment by johnmottole** [comment]
[Final.pdf](https://github.com/johnmottole/ssw322-group1/files/775945/Final.pdf)
